#!usr/bin/env python3
# -*- coding: utf-8 -*-
import math
def quadratic(a,b,c):
	if not isinstance(a,(int,float)) and isinstance(b,(int,float)) and isinstance(c,(int,float)):
		raise TypeError("Error-0:参数数据类型错误！")
	elif a==0:
		if b==0:
			raise TypeError("Error-1:参数a,b不能全为0！")
		else:
			x1=x2=-b/c
	elif (b**2-4*a*c)<0:
		raise TypeError("Error-2:该方程无解！")
	else:
		x1 = (-b + math.sqrt(b**2-4*a*c)) / (2*a)
		x2 = (-b - math.sqrt(b**2-4*a*c)) / (2*a)
	return x1, x2
